
version: '2'

services:
  s3-policy-signer:
    image: s3-policy-signer:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
      - 5858:5858
    volumes:
      - .:/usr/src/app
    command: node --debug=5858 server.js
