
version: '2'

services:
  s3-policy-signer:
    image: s3-policy-signer:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      S3_ACCESS_KEY: <access-key>
      S3_SECRET_KEY: <secret-key>
      S3_BUCKET: <bucket>
      S3_REGION: <region>
    ports:
      - 5000:5000